name: uplaod and download artifacts
on:
  workflow_dispatch:
jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: creating a file
        run: echo "this is a file created for artifact upload and download" > artifacts.txt
      - name: uploading the artifact
        uses: actions/upload-artifact@v6
        with:
          name: my-artifact
          path: artifacts.txt
  download-artifacts:
    runs-on: ubuntu-latest
    needs: upload-artifacts
    steps:
      - name: downloading the artifact
        uses: actions/download-artifact@v6
        with:
          name: my-artifact
      - name: checking the contents of the artifact
        run: cat artifacts.txt
