name: matrix strategy workflow
on:
  pull_request:
strategy:
  matrix:
    python-version: [3.8, 3.9, 3.10]
    os: [ubuntu-latest, windows-latest, macos-latest]
jobs:
  build:
    runs-on: ${{ matrix.os}}
    steps:
      - name: checking out the code
        uses: actions/checkout@v3
      - name: setting up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}